from django.views.generic.base import RedirectView
from django.urls import path, reverse_lazy
from . import views

app_name = 'sdcpeople'

urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('sdcpeople:person-list'))),
    path('person/', RedirectView.as_view(url=reverse_lazy('sdcpeople:person-list'))),
    path('person/create/', views.PersonCreate.as_view(), name='person-create'),
    path('person/<int:pk>/update/', views.PersonUpdate.as_view(), name='person-update'),
    path('person/<int:pk>/detail/', views.PersonDetail.as_view(), name='person-detail'),
    path('person/<int:pk>/delete/', views.PersonSoftDelete.as_view(), name='person-delete'),
    path('person/list/', views.PersonList.as_view(), name='person-list'),
    path('person/<int:pk>/close/', views.PersonClose.as_view(), name="person-close"),
    path('person/<str:copied_from>/copied/', views.PersonList.as_view(), name='person-copied'),
    path('locationcongress/', RedirectView.as_view(url=reverse_lazy('sdcpeople:locationcongress-list'))),
    path('locationcongress/create/', views.LocationCongressCreate.as_view(), name='locationcongress-create'),
    path('locationcongress/<int:pk>/update/', views.LocationCongressUpdate.as_view(), name='locationcongress-update'),
    path('locationcongress/<int:pk>/detail/', views.LocationCongressDetail.as_view(), name='locationcongress-detail'),
    path('locationcongress/<int:pk>/delete/', views.LocationCongressDelete.as_view(), name='locationcongress-delete'),
    path('locationcongress/list/', views.LocationCongressList.as_view(), name='locationcongress-list'),
    path('locationcongress/<int:pk>/close/', views.LocationCongressClose.as_view(), name="locationcongress-close"),
    path('locationstatehouse/', RedirectView.as_view(url=reverse_lazy('sdcpeople:locationstatehouse-list'))),
    path('locationstatehouse/create/', views.LocationStateHouseCreate.as_view(), name='locationstatehouse-create'),
    path('locationstatehouse/<int:pk>/update/', views.LocationStateHouseUpdate.as_view(), name='locationstatehouse-update'),
    path('locationstatehouse/<int:pk>/detail/', views.LocationStateHouseDetail.as_view(), name='locationstatehouse-detail'),
    path('locationstatehouse/<int:pk>/delete/', views.LocationStateHouseDelete.as_view(), name='locationstatehouse-delete'),
    path('locationstatehouse/list/', views.LocationStateHouseList.as_view(), name='locationstatehouse-list'),
    path('locationstatehouse/<int:pk>/close/', views.LocationStateHouseClose.as_view(), name="locationstatehouse-close"),
    path('locationstatesenate/', RedirectView.as_view(url=reverse_lazy('sdcpeople:locationstatesenate-list'))),
    path('locationstatesenate/create/', views.LocationStateSenateCreate.as_view(), name='locationstatesenate-create'),
    path('locationstatesenate/<int:pk>/update/', views.LocationStateSenateUpdate.as_view(), name='locationstatesenate-update'),
    path('locationstatesenate/<int:pk>/detail/', views.LocationStateSenateDetail.as_view(), name='locationstatesenate-detail'),
    path('locationstatesenate/<int:pk>/delete/', views.LocationStateSenateDelete.as_view(), name='locationstatesenate-delete'),
    path('locationstatesenate/list/', views.LocationStateSenateList.as_view(), name='locationstatesenate-list'),
    path('locationstatesenate/<int:pk>/close/', views.LocationStateSenateClose.as_view(), name="locationstatesenate-close"),
    path('locationborough/', RedirectView.as_view(url=reverse_lazy('sdcpeople:locationborough-list'))),
    path('locationborough/create/', views.LocationBoroughCreate.as_view(), name='locationborough-create'),
    path('locationborough/create/_/', views.LocationBoroughCreate.as_view(), name='locationborough-create-popup'),
    path('locationborough/<int:pk>/update/', views.LocationBoroughUpdate.as_view(), name='locationborough-update'),
    path('locationborough/<int:pk>/update/_/', views.LocationBoroughUpdate.as_view(), name='locationborough-update-popup'),
    path('locationborough/<int:pk>/detail/', views.LocationBoroughDetail.as_view(), name='locationborough-detail'),
    path('locationborough/<int:pk>/delete/', views.LocationBoroughDelete.as_view(), name='locationborough-delete'),
    path('locationborough/list/', views.LocationBoroughList.as_view(), name='locationborough-list'),
    path('locationborough/<int:pk>/close/', views.LocationBoroughClose.as_view(), name="locationborough-close"),
    path('locationprecinct/', RedirectView.as_view(url=reverse_lazy('sdcpeople:locationprecinct-list'))),
    path('locationprecinct/create/', views.LocationPrecinctCreate.as_view(), name='locationprecinct-create'),
    path('locationprecinct/create/_/', views.LocationPrecinctCreate.as_view(), name='locationprecinct-create-popup'),
    path('locationprecinct/<int:pk>/update/', views.LocationPrecinctUpdate.as_view(), name='locationprecinct-update'),
    path('locationprecinct/<int:pk>/update/_/', views.LocationPrecinctUpdate.as_view(), name='locationprecinct-update-popup'),
    path('locationprecinct/<int:pk>/detail/', views.LocationPrecinctDetail.as_view(), name='locationprecinct-detail'),
    path('locationprecinct/<int:pk>/delete/', views.LocationPrecinctDelete.as_view(), name='locationprecinct-delete'),
    path('locationprecinct/list/', views.LocationPrecinctList.as_view(), name='locationprecinct-list'),
    path('locationprecinct/<int:pk>/close/', views.LocationPrecinctClose.as_view(), name="locationprecinct-close"),
    path('votingaddress/', RedirectView.as_view(url=reverse_lazy('sdcpeople:votingaddress-list'))),
    path('votingaddress/create/', views.VotingAddressCreate.as_view(), name='votingaddress-create'),
    path('votingaddress/create/_/', views.VotingAddressCreate.as_view(), {'popup':True }, name='votingaddress-create-popup'),
    path('votingaddress/<int:pk>/update/', views.VotingAddressUpdate.as_view(), name='votingaddress-update'),
    path('votingaddress/<int:pk>/update/_/', views.VotingAddressUpdate.as_view(), {'popup':True }, name='votingaddress-update-popup'),
    path('votingaddress/<int:pk>/detail/', views.VotingAddressDetail.as_view(), name='votingaddress-detail'),
    path('votingaddress/<int:pk>/delete/', views.VotingAddressDelete.as_view(), name='votingaddress-delete'),
    path('votingaddress/list/', views.VotingAddressList.as_view(), name='votingaddress-list'),
    path('votingaddress/<int:pk>/close/', views.VotingAddressClose.as_view(), name="votingaddress-close"),
]
