from django.views.generic.base import RedirectView
from django.urls import path, reverse_lazy
from . import views

app_name = 'sdcpeople'

urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('sdcpeople:person-list'))),
    path('person/', RedirectView.as_view(url=reverse_lazy('sdcpeople:person-list'))),
    path('person/create/', views.PersonCreate.as_view(), name='person-create'),
    path('person/<int:pk>/update/', views.PersonUpdate.as_view(), name='person-update'),
    path('person/<int:pk>/detail/', views.PersonDetail.as_view(), name='person-detail'),
    path('person/<int:pk>/delete/', views.PersonDelete.as_view(), name='person-delete'),
    path('person/list/', views.PersonList.as_view(), name='person-list'),
    path('person/list/by/<int:by_value>/<by_parameter>/', views.PersonList.as_view(), name='person-list-by'),
    path('person/csv/', views.PersonCSV.as_view(), name='person-csv'),
    path('person/csvupload/', views.PersonCSVUpload.as_view(), name="person-csvupload"),
    
    path('person/<int:pk>/close/', views.PersonClose.as_view(), name="person-close"),


    path('subcommittee/', RedirectView.as_view(url=reverse_lazy('sdcpeople:subcommittee-list'))),
    path('subcommittee/create/', views.SubCommitteeCreate.as_view(), name='subcommittee-create'),
    path('subcommittee/<int:pk>/update/', views.SubCommitteeUpdate.as_view(), name='subcommittee-update'),
    path('subcommittee/<int:pk>/detail/', views.SubCommitteeDetail.as_view(), name='subcommittee-detail'),
    path('subcommittee/<int:pk>/delete/', views.SubCommitteeDelete.as_view(), name='subcommittee-delete'),
    path('subcommittee/list/', views.SubCommitteeList.as_view(), name='subcommittee-list'),
    path('subcommittee/<int:pk>/close/', views.SubCommitteeClose.as_view(), name="subcommittee-close"),

    path('event/', RedirectView.as_view(url=reverse_lazy('sdcpeople:event-list'))),
    path('event/create/', views.EventCreate.as_view(), name='event-create'),
    path('event/<int:pk>/update/', views.EventUpdate.as_view(), name='event-update'),
    path('event/<int:pk>/detail/', views.EventDetail.as_view(), name='event-detail'),
    path('event/<int:pk>/delete/', views.EventDelete.as_view(), name='event-delete'),
    path('event/list/', views.EventList.as_view(), name='event-list'),
    path('event/<int:pk>/close/', views.EventClose.as_view(), name="event-close"),

    path('savedlist/', RedirectView.as_view(url=reverse_lazy('sdcpeople:savedlist-list'))),
    path('savedlist/create/', views.SavedListCreate.as_view(), name='savedlist-create'),
    path('savedlist/<int:pk>/update/', views.SavedListUpdate.as_view(), name='savedlist-update'),
    path('savedlist/<int:pk>/detail/', views.SavedListDetail.as_view(), name='savedlist-detail'),
    path('savedlist/<int:pk>/delete/', views.SavedListDelete.as_view(), name='savedlist-delete'),
    path('savedlist/list/', views.SavedListList.as_view(), name='savedlist-list'),
    path('savedlist/<int:pk>/close/', views.SavedListClose.as_view(), name="savedlist-close"),


    path('bulkcommunication/', RedirectView.as_view(url=reverse_lazy('sdcpeople:bulkcommunication-list'))),
    path('bulkcommunication/create/', views.BulkCommunicationCreate.as_view(), name='bulkcommunication-create'),
    path('bulkcommunication/<int:pk>/update/', views.BulkCommunicationUpdate.as_view(), name='bulkcommunication-update'),
    path('bulkcommunication/<int:pk>/detail/', views.BulkCommunicationDetail.as_view(), name='bulkcommunication-detail'),
    path('bulkcommunication/<int:pk>/delete/', views.BulkCommunicationDelete.as_view(), name='bulkcommunication-delete'),
    path('bulkcommunication/list/', views.BulkCommunicationList.as_view(), name='bulkcommunication-list'),
    path('bulkcommunication/<int:pk>/close/', views.BulkCommunicationClose.as_view(), name="bulkcommunication-close"),
    path('bulkcommunication/create/_/', views.BulkCommunicationCreate.as_view(), {'popup':True }, name='bulkcommunication-create-popup'),
    path('bulkcommunication/<int:pk>/update/_/', views.BulkCommunicationUpdate.as_view(), {'popup':True }, name='bulkcommunication-update-popup'),


    path('communicationevent/', RedirectView.as_view(url=reverse_lazy('sdcpeople:communicationevent-list'))),
    path('communicationevent/create/', views.CommunicationEventCreate.as_view(), name='communicationevent-create'),
    path('communicationevent/<int:pk>/update/', views.CommunicationEventUpdate.as_view(), name='communicationevent-update'),
    path('communicationevent/<int:pk>/detail/', views.CommunicationEventDetail.as_view(), name='communicationevent-detail'),
    path('communicationevent/<int:pk>/delete/', views.CommunicationEventDelete.as_view(), name='communicationevent-delete'),
    path('communicationevent/list/', views.CommunicationEventList.as_view(), name='communicationevent-list'),
    path('communicationevent/<int:pk>/close/', views.CommunicationEventClose.as_view(), name="communicationevent-close"),
    path('communicationevent/csv/', views.CommunicationEventCSV.as_view(), name='communicationevent-csv'),

    path('locationcity/', RedirectView.as_view(url=reverse_lazy('sdcpeople:locationcity-list'))),
    path('locationcity/create/', views.LocationCityCreate.as_view(), name='locationcity-create'),
    path('locationcity/<int:pk>/update/', views.LocationCityUpdate.as_view(), name='locationcity-update'),
    path('locationcity/<int:pk>/detail/', views.LocationCityDetail.as_view(), name='locationcity-detail'),
    path('locationcity/<int:pk>/delete/', views.LocationCityDelete.as_view(), name='locationcity-delete'),
    path('locationcity/list/', views.LocationCityList.as_view(), name='locationcity-list'),
    path('locationcity/<int:pk>/close/', views.LocationCityClose.as_view(), name="locationcity-close"),

    path('locationcongress/', RedirectView.as_view(url=reverse_lazy('sdcpeople:locationcongress-list'))),
    path('locationcongress/create/', views.LocationCongressCreate.as_view(), name='locationcongress-create'),
    path('locationcongress/<int:pk>/update/', views.LocationCongressUpdate.as_view(), name='locationcongress-update'),
    path('locationcongress/<int:pk>/detail/', views.LocationCongressDetail.as_view(), name='locationcongress-detail'),
    path('locationcongress/<int:pk>/delete/', views.LocationCongressDelete.as_view(), name='locationcongress-delete'),
    path('locationcongress/list/', views.LocationCongressList.as_view(), name='locationcongress-list'),
    path('locationcongress/<int:pk>/close/', views.LocationCongressClose.as_view(), name="locationcongress-close"),
    path('locationstatehouse/', RedirectView.as_view(url=reverse_lazy('sdcpeople:locationstatehouse-list'))),
    path('locationstatehouse/create/', views.LocationStateHouseCreate.as_view(), name='locationstatehouse-create'),
    path('locationstatehouse/<int:pk>/update/', views.LocationStateHouseUpdate.as_view(), name='locationstatehouse-update'),
    path('locationstatehouse/<int:pk>/detail/', views.LocationStateHouseDetail.as_view(), name='locationstatehouse-detail'),
    path('locationstatehouse/<int:pk>/delete/', views.LocationStateHouseDelete.as_view(), name='locationstatehouse-delete'),
    path('locationstatehouse/list/', views.LocationStateHouseList.as_view(), name='locationstatehouse-list'),
    path('locationstatehouse/<int:pk>/close/', views.LocationStateHouseClose.as_view(), name="locationstatehouse-close"),
    path('locationstatesenate/', RedirectView.as_view(url=reverse_lazy('sdcpeople:locationstatesenate-list'))),
    path('locationstatesenate/create/', views.LocationStateSenateCreate.as_view(), name='locationstatesenate-create'),
    path('locationstatesenate/<int:pk>/update/', views.LocationStateSenateUpdate.as_view(), name='locationstatesenate-update'),
    path('locationstatesenate/<int:pk>/detail/', views.LocationStateSenateDetail.as_view(), name='locationstatesenate-detail'),
    path('locationstatesenate/<int:pk>/delete/', views.LocationStateSenateDelete.as_view(), name='locationstatesenate-delete'),
    path('locationstatesenate/list/', views.LocationStateSenateList.as_view(), name='locationstatesenate-list'),
    path('locationstatesenate/<int:pk>/close/', views.LocationStateSenateClose.as_view(), name="locationstatesenate-close"),
    path('locationborough/', RedirectView.as_view(url=reverse_lazy('sdcpeople:locationborough-list'))),
    path('locationborough/create/', views.LocationBoroughCreate.as_view(), name='locationborough-create'),
    path('locationborough/create/_/', views.LocationBoroughCreate.as_view(), name='locationborough-create-popup'),
    path('locationborough/<int:pk>/update/', views.LocationBoroughUpdate.as_view(), name='locationborough-update'),
    path('locationborough/<int:pk>/update/_/', views.LocationBoroughUpdate.as_view(), name='locationborough-update-popup'),
    path('locationborough/<int:pk>/detail/', views.LocationBoroughDetail.as_view(), name='locationborough-detail'),
    path('locationborough/<int:pk>/delete/', views.LocationBoroughDelete.as_view(), name='locationborough-delete'),
    path('locationborough/list/', views.LocationBoroughList.as_view(), name='locationborough-list'),
    path('locationborough/<int:pk>/close/', views.LocationBoroughClose.as_view(), name="locationborough-close"),
    path('locationprecinct/', RedirectView.as_view(url=reverse_lazy('sdcpeople:locationprecinct-list'))),
    path('locationprecinct/create/', views.LocationPrecinctCreate.as_view(), name='locationprecinct-create'),
    path('locationprecinct/create/_/', views.LocationPrecinctCreate.as_view(), name='locationprecinct-create-popup'),
    path('locationprecinct/<int:pk>/update/', views.LocationPrecinctUpdate.as_view(), name='locationprecinct-update'),
    path('locationprecinct/<int:pk>/update/_/', views.LocationPrecinctUpdate.as_view(), name='locationprecinct-update-popup'),
    path('locationprecinct/<int:pk>/detail/', views.LocationPrecinctDetail.as_view(), name='locationprecinct-detail'),
    path('locationprecinct/<int:pk>/delete/', views.LocationPrecinctDelete.as_view(), name='locationprecinct-delete'),
    path('locationprecinct/list/', views.LocationPrecinctList.as_view(), name='locationprecinct-list'),
    path('locationprecinct/<int:pk>/close/', views.LocationPrecinctClose.as_view(), name="locationprecinct-close"),

    path('participation/', RedirectView.as_view(url=reverse_lazy('sdcpeople:participation-list'))),
    path('participation/create/', views.ParticipationCreate.as_view(), name='participation-create'),
    path('participation/create/_/', views.ParticipationCreate.as_view(), name='participation-create-popup'),
    path('participation/<int:pk>/update/', views.ParticipationUpdate.as_view(), name='participation-update'),
    path('participation/<int:pk>/update/_/', views.ParticipationUpdate.as_view(), name='participation-update-popup'),
    path('participation/<int:pk>/detail/', views.ParticipationDetail.as_view(), name='participation-detail'),
    path('participation/<int:pk>/delete/', views.ParticipationDelete.as_view(), name='participation-delete'),
    path('participation/list/', views.ParticipationList.as_view(), name='participation-list'),
    path('participation/<int:pk>/close/', views.ParticipationClose.as_view(), name="participation-close"),

    path('votingaddress/', RedirectView.as_view(url=reverse_lazy('sdcpeople:votingaddress-list'))),
    path('votingaddress/create/', views.VotingAddressCreate.as_view(), name='votingaddress-create'),
    path('votingaddress/create/_/', views.VotingAddressCreate.as_view(), {'popup':True }, name='votingaddress-create-popup'),
    path('votingaddress/<int:pk>/update/', views.VotingAddressUpdate.as_view(), name='votingaddress-update'),
    path('votingaddress/<int:pk>/update/_/', views.VotingAddressUpdate.as_view(), {'popup':True }, name='votingaddress-update-popup'),
    path('votingaddress/<int:pk>/detail/', views.VotingAddressDetail.as_view(), name='votingaddress-detail'),
    path('votingaddress/<int:pk>/delete/', views.VotingAddressDelete.as_view(), name='votingaddress-delete'),
    path('votingaddress/list/', views.VotingAddressList.as_view(), name='votingaddress-list'),
    path('votingaddress/<int:pk>/close/', views.VotingAddressClose.as_view(), name="votingaddress-close"),
]
