# Generated by Django 4.0.3 on 2022-03-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='subcommittee',
            new_name='subcommittees',
        ),
    ]
