# Generated by Django 4.0.3 on 2022-03-16 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sdcpeople', '0002_rename_subcommittee_person_subcommittees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactVoicePhone',
            new_name='ContactVoice',
        ),
        migrations.AddField(
            model_name='duespayment',
            name='person',
            field=models.ForeignKey(default=1, help_text='The person to whom this membership applies', on_delete=django.db.models.deletion.CASCADE, to='sdcpeople.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='person',
            field=models.ForeignKey(default=1, help_text='The person to whom this membership applies', on_delete=django.db.models.deletion.CASCADE, to='sdcpeople.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votingaddress',
            name='street_address',
            field=models.CharField(blank=True, help_text='The street address', max_length=100, verbose_name='street address'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, help_text='The date this change was made', verbose_name='when')),
                ('modelname', models.CharField(help_text='The model to which this change applies', max_length=50, verbose_name='model')),
                ('objectid', models.BigIntegerField(blank=True, help_text='The id of the record that was changed', null=True, verbose_name='object id')),
                ('fieldname', models.CharField(help_text='The that was changed', max_length=50, verbose_name='field')),
                ('old_value', models.TextField(blank=True, help_text='The value of the field before the change', null=True, verbose_name='old value')),
                ('new_value', models.TextField(blank=True, help_text='The value of the field after the change', verbose_name='new value')),
                ('user', models.ForeignKey(help_text='The user who made this change', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-when', 'modelname', 'objectid'),
            },
        ),
    ]
