# Generated by Django 4.0.3 on 2022-03-17 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', '0003_rename_contactvoicephone_contactvoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingaddress',
            name='locationcstatesenate',
        ),
        migrations.AddField(
            model_name='votingaddress',
            name='locationstatesenate',
            field=models.ForeignKey(blank=True, help_text="The person's state senatorial district", null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdcpeople.locationstatesenate', verbose_name='State Senatorial District'),
        ),
        migrations.AlterField(
            model_name='votingaddress',
            name='locationborough',
            field=models.ForeignKey(blank=True, help_text="The person's borough", null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdcpeople.locationborough', verbose_name='Borough'),
        ),
        migrations.AlterField(
            model_name='votingaddress',
            name='locationcongress',
            field=models.ForeignKey(blank=True, help_text="The person's congressional district", null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdcpeople.locationcongress', verbose_name='Congressional District'),
        ),
        migrations.AlterField(
            model_name='votingaddress',
            name='locationmagestrate',
            field=models.ForeignKey(blank=True, help_text="The person's magisterial district", null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdcpeople.locationmagistrate', verbose_name='Magisterial District'),
        ),
        migrations.AlterField(
            model_name='votingaddress',
            name='locationprecinct',
            field=models.ForeignKey(blank=True, help_text="The person's precinct", null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdcpeople.locationprecinct', verbose_name='Precinct'),
        ),
        migrations.AlterField(
            model_name='votingaddress',
            name='locationstatehouse',
            field=models.ForeignKey(blank=True, help_text="The person's house of delegates district", null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdcpeople.locationstatehouse', verbose_name='House of Delegates District'),
        ),
        migrations.AlterField(
            model_name='votingaddress',
            name='street_address',
            field=models.TextField(blank=True, help_text='The street address', verbose_name='street address'),
        ),
    ]
