# Generated by Django 4.0.3 on 2022-03-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', '0004_remove_votingaddress_locationcstatesenate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='quorum_member',
            field=models.BooleanField(default=False, help_text='If this member counts as a quorum', verbose_name='Quorum Member'),
        ),
    ]
