# Generated by Django 4.0.3 on 2022-03-17 19:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', '0005_person_quorum_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(default=datetime.date.today, help_text='The starting date for this membership', verbose_name='effective date')),
            ],
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('membership_status__is_quorum', 'name_last', 'name_first')},
        ),
        migrations.RemoveField(
            model_name='membershiptype',
            name='can_vote',
        ),
        migrations.RemoveField(
            model_name='membershiptype',
            name='is_member',
        ),
        migrations.RemoveField(
            model_name='membershiptype',
            name='is_quorum',
        ),
        migrations.RemoveField(
            model_name='membershiptype',
            name='pays_dues',
        ),
        migrations.RemoveField(
            model_name='person',
            name='quorum_member',
        ),
        migrations.AddField(
            model_name='membershipstatus',
            name='is_member',
            field=models.BooleanField(default=False, help_text='If a persion with type and status counts as a members of the committee', verbose_name='is member'),
        ),
        migrations.AddField(
            model_name='membershipstatus',
            name='membership_type',
            field=models.ForeignKey(default=1, help_text='The type of membership associated with this this status', on_delete=django.db.models.deletion.CASCADE, to='sdcpeople.membershiptype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipstatus',
            name='pays_dues',
            field=models.BooleanField(default=False, help_text='If a person with this type and status of membership is expected to pay dues)', verbose_name='pays dues'),
        ),
        migrations.AddField(
            model_name='person',
            name='membership_status',
            field=models.ForeignKey(help_text="The person's current membership", null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdcpeople.membershipstatus'),
        ),
        migrations.AlterField(
            model_name='membershipstatus',
            name='can_vote',
            field=models.BooleanField(default=False, help_text='If a person with this type and status of membership can vote)', verbose_name='can vote'),
        ),
        migrations.AlterField(
            model_name='membershipstatus',
            name='is_quorum',
            field=models.BooleanField(default=False, help_text='If a person with this type and status of membership is a quorum member)', verbose_name='is quorum'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.AddField(
            model_name='membershiphistory',
            name='membership_status',
            field=models.ForeignKey(help_text='The status of membership for this period', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdcpeople.membershipstatus'),
        ),
        migrations.AddField(
            model_name='membershiphistory',
            name='person',
            field=models.ForeignKey(help_text='The person to whom this membership applies', on_delete=django.db.models.deletion.CASCADE, to='sdcpeople.person'),
        ),
    ]
