# Generated by Django 4.0.3 on 2022-03-20 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', '0006_membershiphistory_alter_person_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="The title of this person's position", max_length=100, verbose_name='title')),
                ('rank', models.IntegerField(default=1000, help_text='A number representing the placement of this person in a list of subcommittee members - default 1000 and any lower number(0,1,2 etc) is higher on the list', verbose_name='list rank')),
            ],
            options={
                'ordering': ['rank', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='membershipstatus',
            options={'ordering': ['-is_quorum', 'membership_type', 'name']},
        ),
        migrations.RemoveField(
            model_name='submembership',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='submembership',
            name='title',
        ),
        migrations.AlterField(
            model_name='membershipstatus',
            name='name',
            field=models.CharField(blank=True, help_text='The name of this membership status', max_length=100, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='submembership',
            name='position',
            field=models.ForeignKey(blank=True, help_text="The person's position on the committee", null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdcpeople.position', verbose_name='positon'),
        ),
    ]
