# Generated by Django 4.0.3 on 2022-03-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', '0007_position_alter_membershipstatus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactvoice',
            name='is_mobile',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Not Mobile'), (2, 'Mobile')], default=0, help_text='If this phone is mobile', verbose_name='is mobile'),
        ),
        migrations.AddField(
            model_name='contactvoice',
            name='label',
            field=models.CharField(blank=True, help_text='The label for this phone, such as "Work" or "Home"', max_length=50, verbose_name='label'),
        ),
    ]
