# Generated by Django 4.0.3 on 2022-03-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', '0008_contactvoice_is_mobile_contactvoice_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactvoice',
            options={'ordering': ['-rank_number', 'number']},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['-rank_number', 'title']},
        ),
        migrations.AlterModelOptions(
            name='subcommittee',
            options={'ordering': ['-rank_number', 'name']},
        ),
        migrations.RemoveField(
            model_name='position',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='subcommittee',
            name='rank',
        ),
        migrations.AddField(
            model_name='contactvoice',
            name='rank_number',
            field=models.IntegerField(default=0, help_text='A number representing the placement of this phone on a list in descending order (ex: if you want this one first, give it a high number like 1000)', verbose_name='rank'),
        ),
        migrations.AddField(
            model_name='position',
            name='rank_number',
            field=models.IntegerField(default=0, help_text='A number representing the placement of this position on a list in descending order (ex if you want this one first, give it a high number like 1000)', verbose_name='rank'),
        ),
        migrations.AddField(
            model_name='subcommittee',
            name='rank_number',
            field=models.IntegerField(default=0, help_text='A number representing the placement of this committee on a list in descending order (ex if you want this one first, give it a high number like 1000)', verbose_name='rank'),
        ),
        migrations.AlterField(
            model_name='contactvoice',
            name='is_mobile',
            field=models.IntegerField(choices=[(0, ''), (1, 'Not Mobile'), (2, 'Mobile')], default=0, help_text='If this phone is mobile', verbose_name='is mobile'),
        ),
    ]
