# Generated by Django 4.0.3 on 2022-03-22 10:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', '0011_rename_locationmagestrate_votingaddress_locationmagistrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.ManyToManyField(help_text="The person's position in the committee", to='sdcpeople.position'),
        ),
        migrations.CreateModel(
            name='PositionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(default=datetime.date.today, help_text='The starting date for this positon', verbose_name='effective date')),
                ('ending_date', models.DateField(blank=True, help_text='The ending date for this positon', null=True, verbose_name='ending date')),
                ('person', models.ForeignKey(help_text='The person to whom this membership applies', on_delete=django.db.models.deletion.CASCADE, to='sdcpeople.person')),
                ('position', models.ForeignKey(help_text='The position for this period', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdcpeople.position')),
            ],
        ),
    ]
