# Generated by Django 4.0.3 on 2022-03-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', '0012_person_position_positionhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='position',
            new_name='positions',
        ),
    ]
