# Generated by Django 4.0.3 on 2022-03-22 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', '0013_rename_position_person_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='positions',
            field=models.ManyToManyField(blank=True, help_text="The person's position in the committee", to='sdcpeople.position'),
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='The title of this link', max_length=100, verbose_name='title')),
                ('href', models.URLField(help_text='The link', max_length=400, verbose_name='href')),
                ('person', models.ForeignKey(help_text='The person to whom this link applies', on_delete=django.db.models.deletion.CASCADE, to='sdcpeople.person')),
            ],
        ),
    ]
