# Generated by Django 4.0.3 on 2022-03-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', '0014_alter_person_positions_links'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
    ]
