# Generated by Django 4.0.3 on 2022-03-23 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', '0015_rename_links_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='The email address', max_length=250, verbose_name='address')),
                ('label', models.CharField(blank=True, help_text='The label for this email account, such as "Work" or "Home"', max_length=50, verbose_name='label')),
                ('rank_number', models.IntegerField(default=0, help_text='A number representing the placement of this email on a list in descending order (ex: if you want this one first, give it a high number like 1000)', verbose_name='rank')),
                ('extra', models.CharField(blank=True, help_text="Extra texting instructions, such as 'Respond to challange after sending the text'", max_length=100, verbose_name='extra')),
                ('alert', models.CharField(blank=True, help_text='Important information about texting, such as "Don\'t text before 10:00am"', max_length=100, verbose_name='alert')),
                ('person', models.ForeignKey(help_text='The person who is contaced with this number', on_delete=django.db.models.deletion.CASCADE, to='sdcpeople.person')),
            ],
            options={
                'ordering': ['-rank_number', 'address'],
            },
        ),
    ]
