# Generated by Django 4.0.3 on 2022-03-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', '0016_contactemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='If this object is soft-deleted', verbose_name='is_deleted'),
        ),
    ]
