# Generated by Django 4.0.3 on 2022-03-23 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sdcpeople', '0017_person_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('is_deleted', 'membership_status__is_quorum', 'name_last', 'name_first')},
        ),
        migrations.CreateModel(
            name='PersonUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(help_text='The person associated with the user', on_delete=django.db.models.deletion.CASCADE, to='sdcpeople.person')),
                ('user', models.ForeignKey(help_text='The user associated with the person', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
