# Generated by Django 4.0.6 on 2022-07-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', '0019_person_name_prefix_person_name_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='vb_campaign_id',
            field=models.CharField(blank=True, help_text='The votebuilder "My Campaign" van id for this campaign or committee', max_length=20, verbose_name='campaign VANID'),
        ),
        migrations.AddField(
            model_name='person',
            name='vb_voter_id',
            field=models.CharField(blank=True, help_text='The votebuilder "My Voters" van id', max_length=20, verbose_name='voter file VANID'),
        ),
    ]
