# Generated by Django 4.0.6 on 2022-07-24 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', '0020_person_vb_campaign_id_person_vb_voter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the type of event', max_length=40, verbose_name='Event Type')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name or title of event', max_length=40, verbose_name='Event Name/Title')),
                ('event_type', models.ForeignKey(blank=True, help_text='The type of event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdcpeople.eventtype')),
            ],
        ),
    ]
