# Generated by Django 4.0.6 on 2022-07-24 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', '0021_eventtype_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name or title of event', max_length=40, verbose_name='Event Name/Title')),
                ('action_name', models.CharField(help_text='An action phrase for this ', max_length=60, verbose_name='Action Name')),
                ('rank_number', models.IntegerField(default=0, help_text='A number representing the placement of this level on a list in ascending order (ex if you want this one first, give it a low number like 0)', verbose_name='rank')),
            ],
            options={
                'ordering': ['rank_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-when']},
        ),
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['rank_number']},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-when', 'modelname', 'objectid']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['is_deleted', 'membership_status__is_quorum', 'name_last', 'name_first']},
        ),
        migrations.AddField(
            model_name='event',
            name='when',
            field=models.DateField(default='1/1/2000', help_text='The date of the event', verbose_name='when'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtype',
            name='rank_number',
            field=models.IntegerField(default=0, help_text='A number representing the placement of this event type on a list in ascending order (ex if you want this one first, give it a low number like 0)', verbose_name='rank'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_level', models.ForeignKey(blank=True, help_text='The way in which this person is assocated with this event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdcpeople.attendancelevel')),
                ('event', models.ForeignKey(help_text='The event that this person attended (or was othersize associated with)', on_delete=django.db.models.deletion.CASCADE, to='sdcpeople.event')),
                ('person', models.ForeignKey(help_text='The person who attended (or was otherwise associated with) the event', on_delete=django.db.models.deletion.CASCADE, to='sdcpeople.person')),
            ],
        ),
    ]
