# Generated by Django 4.0.6 on 2022-07-25 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', '0022_attendancelevel_alter_event_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(help_text='The event that this person attended (or was othersize associated with)', on_delete=django.db.models.deletion.CASCADE, to='sdcpeople.event')),
            ],
        ),
        migrations.RenameModel(
            old_name='AttendanceLevel',
            new_name='ParticipationLevel',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.AddField(
            model_name='participation',
            name='participation_level',
            field=models.ForeignKey(blank=True, help_text='The way in which this person is assocated with this event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdcpeople.participationlevel'),
        ),
        migrations.AddField(
            model_name='participation',
            name='person',
            field=models.ForeignKey(help_text='The person who attended (or was otherwise associated with) the event', on_delete=django.db.models.deletion.CASCADE, to='sdcpeople.person'),
        ),
    ]
