# Generated by Django 4.0.6 on 2022-08-12 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', '0023_participation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'City or County',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='votingaddress',
            name='locationcity',
            field=models.ForeignKey(blank=True, help_text="The person's city or county", null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdcpeople.locationcity', verbose_name='City or County'),
        ),
    ]
