# Generated by Django 4.0.6 on 2022-08-13 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sdcpeople', '0024_locationcity_votingaddress_locationcity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='The name of the model for which this action applies', max_length=100, verbose_name='model_name')),
                ('when', models.DateTimeField(auto_now_add=True, help_text='The date this change was made', verbose_name='when')),
                ('details', models.TextField(help_text='The details of this action', verbose_name='details')),
                ('action_label', models.CharField(blank=True, help_text='A flag to be set for certain actions, such as a CSV Upload event', max_length=100, verbose_name='recordset action')),
                ('user', models.ForeignKey(help_text='The user who made this change', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-when'],
            },
        ),
        migrations.CreateModel(
            name='RecordactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.ForeignKey(help_text='The person for which this action applies', on_delete=django.db.models.deletion.CASCADE, to='sdcpeople.person')),
                ('recordact', models.ForeignKey(help_text='The recordaction which applies to this object', on_delete=django.db.models.deletion.CASCADE, to='sdcpeople.recordaction')),
            ],
        ),
    ]
