# Generated by Django 4.0.6 on 2022-08-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', '0025_recordaction_recordactperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordaction',
            name='object_name',
            field=models.CharField(blank=True, help_text='The name of the object to which this action applies', max_length=100, verbose_name='object_name'),
        ),
    ]
