# Generated by Django 4.0.6 on 2022-08-14 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', '0026_recordaction_object_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkRecordAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='The name of the bulk action', max_length=100, verbose_name='bulk action name')),
                ('when', models.DateTimeField(auto_now_add=True, help_text='The date this action occured', verbose_name='when')),
            ],
        ),
        migrations.AlterModelOptions(
            name='recordactperson',
            options={'ordering': ('recordact',)},
        ),
        migrations.RemoveField(
            model_name='recordaction',
            name='action_label',
        ),
        migrations.AlterField(
            model_name='recordaction',
            name='model_name',
            field=models.CharField(help_text='The name of the model for which this action applies', max_length=100, verbose_name='model name'),
        ),
        migrations.AlterField(
            model_name='recordaction',
            name='object_name',
            field=models.CharField(blank=True, help_text='The name of the object to which this action applies', max_length=100, verbose_name='object name'),
        ),
        migrations.AddField(
            model_name='recordaction',
            name='bulk_recordact',
            field=models.ForeignKey(blank=True, help_text='The bulk action of which this record action is a part, such as a CSV Upload', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdcpeople.bulkrecordaction'),
        ),
    ]
