# Generated by Django 4.0.6 on 2022-08-14 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', '0027_bulkrecordaction_alter_recordactperson_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='The name of the bulk action', max_length=100, verbose_name='bulk action name')),
                ('when', models.DateTimeField(auto_now_add=True, help_text='The date this action occured', verbose_name='when')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='The name of the bulk action', max_length=100, verbose_name='bulk action name')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, help_text='The date this communication was made', verbose_name='when')),
                ('details', models.TextField(help_text='The details of this communication', verbose_name='details')),
                ('bulk_communication', models.ForeignKey(blank=True, help_text='The bulk communication of which this communication is a part, such as an invitation to an event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdcpeople.bulkcommunication')),
                ('target', models.ForeignKey(help_text='The person who was contacted', on_delete=django.db.models.deletion.CASCADE, related_name='communication_as_target', to='sdcpeople.person')),
                ('volunteer', models.ForeignKey(blank=True, help_text='The person made the contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_as_volunteer', to='sdcpeople.person')),
            ],
            options={
                'ordering': ('-when',),
            },
        ),
    ]
