# Generated by Django 4.0.6 on 2022-08-14 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', '0029_alter_communicationevent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The committee name', max_length=100, verbose_name='name')),
                ('when', models.DateTimeField(auto_now_add=True, help_text='The date this action occured', verbose_name='when')),
            ],
            options={
                'ordering': ['-when', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ListMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savedlist', models.ForeignKey(help_text='The kust on which the person is', on_delete=django.db.models.deletion.CASCADE, to='sdcpeople.savedlist')),
                ('person', models.ForeignKey(help_text='The person who is on the list', on_delete=django.db.models.deletion.CASCADE, to='sdcpeople.person')),
            ],
            options={
                'ordering': ('savedlist',),
            },
        ),
    ]
