# Generated by Django 4.1.1 on 2022-09-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', '0031_rename_peoplelist_savedlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedlist',
            name='name',
            field=models.CharField(help_text='The name of the saved list', max_length=100, verbose_name='name'),
        ),
    ]
