# Generated by Django 4.1.7 on 2023-05-20 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sdcpeople', '0032_alter_savedlist_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedlist',
            options={'ordering': ['created_by', 'name', '-when']},
        ),
        migrations.AddField(
            model_name='savedlist',
            name='created_by',
            field=models.ForeignKey(help_text='The user who created this list', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedlist',
            name='shared',
            field=models.IntegerField(choices=[(0, 'Private'), (1, 'Public (Readable)')], default=1, help_text='If this list can be viewed by others'),
        ),
        migrations.AlterField(
            model_name='savedlist',
            name='when',
            field=models.DateTimeField(auto_now_add=True, help_text='The date this list was created', verbose_name='when'),
        ),
    ]
