# Generated by Django 4.1.7 on 2023-05-20 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sdcpeople', '0033_alter_savedlist_options_savedlist_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedlist',
            options={'ordering': ['owner', 'name', '-when']},
        ),
        migrations.RemoveField(
            model_name='savedlist',
            name='created_by',
        ),
        migrations.AddField(
            model_name='savedlist',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user who ownes this list', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listmembership',
            name='savedlist',
            field=models.ForeignKey(help_text='The list on which the person is', on_delete=django.db.models.deletion.CASCADE, to='sdcpeople.savedlist'),
        ),
    ]
